title: CMIP6 Data Hackathon
menu_title: CMIP6 Data Hack<span class="hide-very-narrow">athon</span><br><small><span class="hide-very-narrow">in association</span> with the Met Office & Bristol</small>
author: University of Bristol Jean Golding Institute & Cabot Institute, 
  Met Office Academic Partnership
description:
  The MOAP CMIP6 Hackathon is a 3-day hackathon event, organised by the
  University of Bristolâ€™s Jean Golding Institute and Cabot Institute. Over the
  course of the event, teams of academic researchers from across the UK will
  work on research questions set by the MOAP partners related to earth-system
  science and CMIP6 data.
url: "https://cmip6moap.github.io"
github_username: cmip6moap 
theme: minima
header_pages:
  - registration.md
  - projects.md
  - agenda.md
  - resources.md
  - about.md
